In [1]:
import json
import pandas as pd
import requests

from bs4 import BeautifulSoup
from random import randint, random, seed

In [3]:
#### I need to make this work with the reformatting of CT data to sentence level.

# df_bert = build_dataset_for_bert(
#     result_sets, test_year, top_n, topics_set,
#     subset_columns, return_fields,
#     whoosh_idx_path, trial_topics_path,
#     df_missing_save_path, fields_to_keep
# )

# print(df_bert.columns)
# print("df_bert.head()")
# print(df_bert.head())
# print(df_bert["disease"].isna().value_counts())
# print(df_bert["gene"].isna().value_counts())

# # PROCESS INTO BERT INPUT SEQ
# # if test:
#     # df_bert.drop("id_y", inplace=True, axis=1)
#     # df_bert = df_bert.rename(columns={"id_x": "id"})

# df_bert = process_validation_data_raw(df_bert, global_var)
# print("df_bert.head() after process_validation_data_raw")
# print(df_bert.head())
# print(df_bert["disease"].isna().value_counts())
# print(df_bert["gene"].isna().value_counts())

In [1]:
import BertSeqSentFinetune

Using TensorFlow backend.


ModuleNotFoundError: No module named 'bert_seq_sent'

In [142]:
import pandas as pd

df = pd.read_pickle("../data/df_bert_tmp.pickle")
print(df.shape)
df.head()

(100, 9)


topic           id       id_topic  \
0     9  NCT01874665  NCT01874665_9   
1     9  NCT01110668  NCT01110668_9   
2     9  NCT02576080  NCT02576080_9   
3     9  NCT02336724  NCT02336724_9   
4     9  NCT02776878  NCT02776878_9   

                                       brief_summary  \
0  The purpose of this study is to evaluate the e...   
1  This study will assess time-to-disease progres...   
2  Following the ACOSOG Z9001trial, imatinib rece...   
3  Famitinib is a tyrosin-inhibitor agent targeti...   
4  The purpose of this study is to determine whet...   

                                         brief_title  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  Evaluation of Nilotinib In Patients With Advan...   
2  Efficacy of Imatinib in Patients With Intermed...   
3  A Study of Famitinib in Patients With Gastroin...   
4  A Clinical Trial Evaluating the Efficacy and S...   

                          disease                       gene  \
0  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
1  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
2  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
3  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
4  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   

                                       brief_t_and_s  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  Evaluation of Nilotinib In Patients With Advan...   
2  Efficacy of Imatinib in Patients With Intermed...   
3  A Study of Famitinib in Patients With Gastroin...   
4  A Clinical Trial Evaluating the Efficacy and S...   

                                             d_and_g  
0  Gastrointestinal stromal tumor, KIT Exon 9 (A5...  
1  Gastrointestinal stromal tumor, KIT Exon 9 (A5...  
2  Gastrointestinal stromal tumor, KIT Exon 9 (A5...  
3  Gastrointestinal stromal tumor, KIT Exon 9 (A5...  
4  Gastrointestinal stromal tumor, KIT Exon 9 (A5...

In [143]:
df.topic.unique()

array(['9', '10'], dtype=object)

In [78]:
for i in range(1):
    print(df.brief_t_and_s[i])
    print(df.brief_t_and_s[i].split(". "))

A Phase 2 Trial of Ponatinib in Patients With Metastatic and/or Unresectable Gastrointestinal Stromal Tumor. The purpose of this study is to evaluate the efficacy and safety of ponatinib in patients with metastatic and/or unresectable gastrointestinal stromal tumor (GIST) following failure of prior tyrosine kinase inhibitor (TKI) therapy.
['A Phase 2 Trial of Ponatinib in Patients With Metastatic and/or Unresectable Gastrointestinal Stromal Tumor', 'The purpose of this study is to evaluate the efficacy and safety of ponatinib in patients with metastatic and/or unresectable gastrointestinal stromal tumor (GIST) following failure of prior tyrosine kinase inhibitor (TKI) therapy.']


In [82]:
df_subset = df[(df["id"] == "NCT01874665") | (df["id"] == "NCT01110668")]
# df_subset["brief_t_and_s"] = df_subset["brief_t_and_s"].apply(lambda x: x.split(". "))
# df_subset

In [89]:
df_subset["all_seq"] = df_subset["brief_t_and_s"] + " " + df_subset["d_and_g"]
df_subset

/Users/xu081/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


topic           id       id_topic  \
0     9  NCT01874665  NCT01874665_9   
1     9  NCT01110668  NCT01110668_9   

                                       brief_summary  \
0  The purpose of this study is to evaluate the e...   
1  This study will assess time-to-disease progres...   

                                         brief_title  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  Evaluation of Nilotinib In Patients With Advan...   

                          disease                       gene  \
0  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
1  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   

                                       brief_t_and_s  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  Evaluation of Nilotinib In Patients With Advan...   

                                             d_and_g  \
0  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
1  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   

                                             all_seq  
0  A Phase 2 Trial of Ponatinib in Patients With ...  
1  Evaluation of Nilotinib In Patients With Advan...

In [90]:
df_subset["all_seq"][1]

'Evaluation of Nilotinib In Patients With Advanced Gastrointestinal Stromal Tumor (GIST). This study will assess time-to-disease progression in patients with advanced gastrointestinal stromal tumor (GIST) previously treated with imatinib ≥600 mg. Gastrointestinal stromal tumor, KIT Exon 9 (A502_Y503dup)'

In [91]:
df_subset["all_seq"] = df_subset["all_seq"].apply(lambda x: x.split(". "))

/Users/xu081/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [92]:
df_subset = df_subset.explode("all_seq").reset_index()
df_subset

index topic           id       id_topic  \
0      0     9  NCT01874665  NCT01874665_9   
1      0     9  NCT01874665  NCT01874665_9   
2      0     9  NCT01874665  NCT01874665_9   
3      1     9  NCT01110668  NCT01110668_9   
4      1     9  NCT01110668  NCT01110668_9   
5      1     9  NCT01110668  NCT01110668_9   

                                       brief_summary  \
0  The purpose of this study is to evaluate the e...   
1  The purpose of this study is to evaluate the e...   
2  The purpose of this study is to evaluate the e...   
3  This study will assess time-to-disease progres...   
4  This study will assess time-to-disease progres...   
5  This study will assess time-to-disease progres...   

                                         brief_title  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  A Phase 2 Trial of Ponatinib in Patients With ...   
2  A Phase 2 Trial of Ponatinib in Patients With ...   
3  Evaluation of Nilotinib In Patients With Advan...   
4  Evaluation of Nilotinib In Patients With Advan...   
5  Evaluation of Nilotinib In Patients With Advan...   

                          disease                       gene  \
0  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
1  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
2  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
3  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
4  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   
5  Gastrointestinal stromal tumor  KIT Exon 9 (A502_Y503dup)   

                                       brief_t_and_s  \
0  A Phase 2 Trial of Ponatinib in Patients With ...   
1  A Phase 2 Trial of Ponatinib in Patients With ...   
2  A Phase 2 Trial of Ponatinib in Patients With ...   
3  Evaluation of Nilotinib In Patients With Advan...   
4  Evaluation of Nilotinib In Patients With Advan...   
5  Evaluation of Nilotinib In Patients With Advan...   

                                             d_and_g  \
0  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
1  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
2  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
3  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
4  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   
5  Gastrointestinal stromal tumor, KIT Exon 9 (A5...   

                                             all_seq  
0  A Phase 2 Trial of Ponatinib in Patients With ...  
1  The purpose of this study is to evaluate the e...  
2  Gastrointestinal stromal tumor, KIT Exon 9 (A5...  
3  Evaluation of Nilotinib In Patients With Advan...  
4  This study will assess time-to-disease progres...  
5  Gastrointestinal stromal tumor, KIT Exon 9 (A5...

In [38]:
df_subset.brief_t_and_s[1]

'The purpose of this study is to evaluate the efficacy and safety of ponatinib in patients with metastatic and/or unresectable gastrointestinal stromal tumor (GIST) following failure of prior tyrosine kinase inhibitor (TKI) therapy.'

## Evaluation Results Wrangling

In [15]:
tmp = pd.read_pickle("../data/df_bert_tmp.pickle")
tmp.head()

topic           id       id_topic  \
0     9  NCT01320085  NCT01320085_9   
1     9  NCT02645149  NCT02645149_9   
2     9  NCT02357732  NCT02357732_9   
3     9  NCT01941927  NCT01941927_9   
4     9  NCT02138292  NCT02138292_9   

                                       brief_summary  \
0  The study will assess the safety and efficacy ...   
1  This is a patient oriented translational resea...   
2  This study evaluates nivolumab in combination ...   
3  This is a multicenter phase II clinical study ...   
4  The study is a prospective, single-arm, one-si...   

                                         brief_title   disease         gene  \
0  A Phase II Study of Single Agent MEK162 in Pat...  melanoma  NRAS (Q61L)   
1  Molecular Profiling and Matched Targeted Thera...  melanoma  NRAS (Q61L)   
2  Study of the Anti-PD-1 Antibody Nivolumab in C...  melanoma  NRAS (Q61L)   
3  Trametinib With GSK2141795 in BRAF Wild-type M...  melanoma  NRAS (Q61L)   
4  A Phase 1B Clinical Trial of Trametinib Plus D...  melanoma  NRAS (Q61L)   

                                       brief_t_and_s                d_and_g  
0  A Phase II Study of Single Agent MEK162 in Pat...  melanoma, NRAS (Q61L)  
1  Molecular Profiling and Matched Targeted Thera...  melanoma, NRAS (Q61L)  
2  Study of the Anti-PD-1 Antibody Nivolumab in C...  melanoma, NRAS (Q61L)  
3  Trametinib With GSK2141795 in BRAF Wild-type M...  melanoma, NRAS (Q61L)  
4  A Phase 1B Clinical Trial of Trametinib Plus D...  melanoma, NRAS (Q61L)

In [18]:
tmp.shape

(500, 9)

In [17]:
tmp.topic.unique()

array(['9', '10', '11', '12', '13', '14', '15', '16', '17', '18'],
      dtype=object)

In [6]:
import pickle

with open("../debug_data/reg_pred_arr.pickle", "rb") as f:
    pred_arr = pickle.load(f)

with open("../debug_data/topics_id.pickle", "rb") as f:
    topics_id = pickle.load(f)

with open("../debug_data/doc_id.pickle", "rb") as f:
    doc_id = pickle.load(f)

In [7]:
pred_arr[:5]

array([[ 0.35273436, -0.8788711 ],
       [ 0.11356196,  0.6403564 ],
       [ 0.20966041,  0.22552927],
       [-0.03923824,  0.57529896],
       [ 0.11194965,  0.721154  ]], dtype=float32)

In [12]:
topics_id

array([ 9, 10, 10, 10,  9, 10,  9, 10,  9, 10,  9,  9, 10, 10, 10,  9,  9,
        9,  9, 10, 10,  9, 10, 10, 10, 10,  9,  9,  9, 10, 10, 10, 10,  9,
        9,  9, 10,  9,  9, 10, 10,  9,  9,  9, 10, 10,  9,  9,  9,  9,  9,
        9,  9,  9,  9, 10, 10,  9,  9, 10, 10,  9,  9,  9, 10,  9,  9, 10,
        9, 10, 10,  9, 10,  9,  9,  9, 10, 10,  9, 10,  9, 10,  9,  9, 10,
       10,  9,  9, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9, 10, 10,  9,  9,
        9,  9, 10, 10,  9,  9, 10, 10, 10,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9,  9,  9,  9,  9, 10,  9, 10, 10,  9,  9, 10, 10,  9, 10,  9,
        9,  9, 10,  9, 10, 10, 10,  9, 10,  9, 10, 10, 10,  9,  9,  9,  9,
       10, 10,  9,  9,  9, 10,  9,  9, 10, 10, 10,  9,  9, 10,  9,  9, 10,
       10, 10, 10,  9,  9,  9, 10,  9, 10,  9, 10, 10, 10, 10,  9,  9,  9,
        9, 10, 10, 10, 10,  9,  9, 10,  9,  9, 10,  9, 10, 10,  9,  9,  9,
        9, 10,  9, 10,  9, 10,  9,  9, 10,  9, 10, 10, 10, 10,  9, 10, 10,
        9,  9,  9,  9, 10

In [140]:
doc_id_test = "NCT00112632"

In [125]:
doc_id

array(['NCT01970696', 'NCT00769782', 'NCT01110668', 'NCT02576080',
       'NCT01970696', 'NCT01970696', 'NCT00507273', 'NCT02576080',
       'NCT00112632', 'NCT00500188', 'NCT00500188', 'NCT01970696',
       'NCT02576080', 'NCT00507273', 'NCT02576080', 'NCT00103168',
       'NCT02576080', 'NCT02776878', 'NCT02576080', 'NCT00457743',
       'NCT00954655', 'NCT02576080', 'NCT02576080', 'NCT01970696',
       'NCT01874665', 'NCT00278876', 'NCT02576080', 'NCT00507273',
       'NCT00954655', 'NCT00457743', 'NCT01874665', 'NCT00278876',
       'NCT02576080', 'NCT02606097', 'NCT00112632', 'NCT00685828',
       'NCT01970696', 'NCT02576080', 'NCT01970696', 'NCT00500188',
       'NCT02336724', 'NCT00278876', 'NCT00507273', 'NCT02576080',
       'NCT00500188', 'NCT01970696', 'NCT00954655', 'NCT00685828',
       'NCT01970696', 'NCT02931981', 'NCT01970696', 'NCT02576080',
       'NCT00278876', 'NCT02576080', 'NCT00507273', 'NCT02576080',
       'NCT02576080', 'NCT02336724', 'NCT00500188', 'NCT025760

In [120]:
import numpy as np
from collections import defaultdict

def softmax(y_pred):
    y_max = np.max(y_pred, axis=1, keepdims=True)

    y_norm = y_pred - y_max
    return np.exp(y_norm)/np.sum(np.exp(y_norm), axis=1, keepdims=True)

def pool(pred_arr, topics_eval_arr, doc_id_eval_arr, pool_func=max):
    y_probs = softmax(pred_arr)
    y_logits = y_probs[:, 1]

    dict_y = defaultdict(list)
    dict_topic = defaultdict(int)
    
    for y, top, doc in zip(y_logits, topics_eval_arr, doc_id_eval_arr):
        dict_y[doc].append(y)
    #     dict_y[doc] = max(dict_y[doc], y)
        dict_topic[doc] = top
        
    assert dict_y.keys() == dict_topic.keys()

    reg_pred_pooled = []
    topics_id_pooled = []
    doc_id_pooled = []

    for k in dict_y.keys():
        doc_id_pooled.append(k)
        reg_pred_pooled.append(pool_func(dict_y[k]))
        topics_id_pooled.append(dict_topic[k])
        
    return doc_id_pooled, topics_id_pooled, reg_pred_pooled

In [121]:
pool(pred_arr, topics_id, doc_id, pool_func=max)

(['NCT01970696',
  'NCT00769782',
  'NCT01110668',
  'NCT02576080',
  'NCT00507273',
  'NCT00112632',
  'NCT00500188',
  'NCT00103168',
  'NCT02776878',
  'NCT00457743',
  'NCT00954655',
  'NCT01874665',
  'NCT00278876',
  'NCT02606097',
  'NCT00685828',
  'NCT02336724',
  'NCT02931981',
  'NCT01028222'],
 [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
 [0.7543163,
  0.7688382,
  0.71365803,
  0.7616607,
  0.69012654,
  0.75919855,
  0.7202015,
  0.75849843,
  0.69941634,
  0.7326614,
  0.7380424,
  0.7525378,
  0.7221952,
  0.6832619,
  0.74945486,
  0.7721589,
  0.7744627,
  0.7664504])

In [64]:
softmax(pred_arr)[:, 1]

array([0.6860049 , 0.21482395, 0.6929103 , 0.72800463, 0.25210243,
       0.74144435, 0.6914381 , 0.20664051, 0.3599593 , 0.7580189 ,
       0.64439857, 0.7535769 , 0.73707116, 0.6214963 , 0.72103554,
       0.25979286, 0.76617956, 0.35539418, 0.7449551 , 0.7331062 ,
       0.7433449 , 0.73464924, 0.5196218 , 0.73131764, 0.3711793 ,
       0.78040487, 0.29600766, 0.713917  , 0.6086964 , 0.58029574,
       0.4393941 , 0.69983584, 0.76012355, 0.7736882 , 0.7604168 ,
       0.68675697, 0.26201504, 0.7397841 , 0.26510096, 0.7093974 ,
       0.6084481 , 0.73652095, 0.6915614 , 0.5598929 , 0.6964478 ,
       0.47069928, 0.72691417, 0.63378584, 0.7470343 , 0.56665665,
       0.30160254, 0.6992863 , 0.7409297 , 0.7371106 , 0.38604957,
       0.7656258 , 0.6384754 , 0.19972505, 0.707643  , 0.7290609 ,
       0.7331701 , 0.7397586 , 0.66761416, 0.7016448 , 0.3718925 ,
       0.4169405 , 0.7348521 , 0.7362602 , 0.67583674, 0.6285177 ,
       0.7742613 , 0.73979336, 0.7429048 , 0.6315047 , 0.76405

In [97]:
test_y = y_logits[:10]
print(test_y)
test_doc = ["a" for i in range(5)] + ["b" for j in range(5)]
print(test_doc)

[0.6860049  0.21482395 0.6929103  0.72800463 0.25210243 0.74144435
 0.6914381  0.20664051 0.3599593  0.7580189 ]
['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b']


In [109]:


dict_y = defaultdict(list)
dict_topic = defaultdict(int)

y_logits = softmax(pred_arr)[:, 1]

for y, top, doc in zip(test_y, topics_id, test_doc):
    dict_y[doc].append(y)
#     dict_y[doc] = max(dict_y[doc], y)
    dict_topic[doc] = top

In [110]:
dict_y

defaultdict(list,
            {'a': [0.6860049, 0.21482395, 0.6929103, 0.72800463, 0.25210243],
             'b': [0.74144435, 0.6914381, 0.20664051, 0.3599593, 0.7580189]})

In [111]:
dict_topic

defaultdict(int, {'a': 9, 'b': 9})

In [112]:
assert dict_y.keys() == dict_topic.keys()

reg_pred_pooled = []
topics_id_pooled = []
doc_id_pooled = []

for k in dict_y.keys():
    doc_id_pooled.append(k)
    reg_pred_pooled.append(max(dict_y[k]))
    topics_id_pooled.append(dict_topic[k])

In [113]:
print(reg_pred_pooled)
print(topics_id_pooled)
print(doc_id_pooled)

[0.72800463, 0.7580189]
[9, 9]
['a', 'b']


In [44]:
reg_pred_arr

array([[-0.20712236,  0.57438487],
       [ 0.5905098 , -0.70557946],
       [-0.10716864,  0.70659214],
       [-0.17395064,  0.81057155],
       [ 0.56638336, -0.52104723],
       [-0.18735686,  0.86613226],
       [-0.20150203,  0.6053491 ],
       [ 0.62010986, -0.72518593],
       [ 0.3149576 , -0.26058316],
       [-0.20358774,  0.938261  ],
       [-0.06486064,  0.52964646],
       [-0.22949019,  0.8882906 ],
       [-0.2015392 ,  0.8292618 ],
       [ 0.01364675,  0.5095508 ],
       [-0.16607301,  0.783531  ],
       [ 0.37155414, -0.67549133],
       [-0.19298437,  0.99387854],
       [ 0.33315885, -0.2622525 ],
       [-0.18953887,  0.8823457 ],
       [-0.25498202,  0.75545776],
       [-0.22706097,  0.836366  ],
       [-0.24012128,  0.77821934],
       [ 0.0585477 ,  0.13707517],
       [-0.24820416,  0.7531136 ],
       [ 0.30365503, -0.22350577],
       [-0.23777398,  1.0302534 ],
       [ 0.42597854, -0.44040364],
       [-0.22712466,  0.68736005],
       [-0.07097526,

In [24]:
x = pd.read_pickle("../debug_data/self_attribs.pickle")
x[1050]

'12'